[build]
base = "ConstructionManagmentFront/ConstructionManagmentFront"
command = "npm install --legacy-peer-deps && npm run build -- --configuration production"
publish = "dist/ConstructionManagmentFront"

[[redirects]]
from = "/api/*"
to = "https://constructionmanagment-production.up.railway.app/api/:splat"
status = 200
force = true
