[build]
base = "ConstructionManagmentFront/ConstructionManagmentFront"
command = "npm run build -- --configuration production"
publish = "dist/ConstructionManagmentFront"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
from = "/api/*"
to = "https://constructionmanagment-production.up.railway.app/api/:splat"
status = 200
force = true
